version: 5.1.0
variant: default
logo: /img/logo.svg
head:
    favicon: /img/favicon.svg
    manifest:
        name: Sworld的博客
        short_name: Sw的博客
        start_url: http://blog.sworld.blog
        theme_color:
        background_color:
        display: standalone
        icons:
            - src: ""
              sizes: ""
              type:
    open_graph:
        title:
        type:
        url:
        image:
        site_name:
        author:
        description:
        twitter_card:
        twitter_id:
        twitter_site:
        google_plus:
        fb_admins:
        fb_app_id:
    structured_data:
        title:
        description:
        url:
        author:
        publisher:
        publisher_logo:
        image:
    meta:
        - ""
    rss:
navbar:
    menu:
        主页: /
        存档: /archives
        标签: /tags
        关于我: /about
    links:
        View Source on GitHub:
            icon: fab fa-github
            url: https://github.com/mcthesw/mcthesw.github.io
footer:
    links:
        View Source on GitHub:
            icon: fab fa-github
            url: https://github.com/mcthesw/mcthesw.github.io
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
comment:
    type: giscus
    repo: mcthesw/sworld-blog
    repoId: R_kgDOHffXoA # 必填项
    category: Announcements # 可选填，默认为 Announcements
    categoryId: DIC_kwDOHffXoM4CiL_b # 必填项
    mapping: title # 可选填，默认为 pathname
    strict: false # 可选填
    reactionsEnabled: true # 可选填
    emitMetadata: false # 可选填
    inputPosition: top # 可选填，默认为 top
    theme: noborder_light # 可选填
    lang: zh-CN # 可选填，默认为 en
    lazy: true # 可选填，默认为 false

donates:
    - type: afdian
      url: https://afdian.com/a/Sworld
    - type: wechat
      qrcode: images/sponsor_wechat.png
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    - position: left
      type: profile
      author: Sworld
      author_title: The only way to do great work is to love what you do.
      location: China
      avatar: https://avatars.githubusercontent.com/u/61224072
      avatar_rounded: true
      gravatar:
      follow_link: https://github.com/mcthesw
      social_links:
          Github:
              icon: fab fa-github
              url: https://github.com/mcthesw
          Bilibili:
              icon: fab fa-youtube
              url: https://space.bilibili.com/4087637
    - position: left
      type: tags
    - position: left
      type: toc
      index: true
      collapsed: true
      depth: 3
    - position: left
      type: recent_posts
    - position: left
      type: archives
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id:
    bing_webmaster:
        tracking_id:
    busuanzi: false
    cnzz:
        id:
        web_id:
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id:
    hotjar:
        site_id:
    katex: true
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project:
        security:
    twitter_conversion_tracking:
        pixel_id:
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
